title: tschuba25
theme: just-the-docs

# Optional plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Navigation order override
nav_order: 1

# (Optional) You can disable post navigation arrows
minima:
  show_nav: true
